bootstrap:
  source:
    type: file
    path: /data/events
  workdir: /data/bootstrap

inference:
  port: 8080
  host: "0.0.0.0"
  source:
    type: rest
  state:
    type: redis
    host: redis
    format: json

models:
  xgboost:
    type: lambdamart
    path: /data/xgboost.model
    backend:
      type: xgboost
      iterations: 10
      seed: 0
    weights:
      click: 1
    features:
      - pesticide
      - fertilizer
      - crops
      - land_area
      - ctr
      - liked_fertilizer
      - visitor_click_count
      - global_item_click_count
      - day_item_click_count
features:
  - name: pesticide
    type: string
    scope: item
    source: item.pesticide
    values:
      - pesticide_1
      - pesticide_2
      - pesticide_3

  - name: fertilizer
    type: string
    scope: item
    source: item.fertilizer
    values:
      - fertilizer_1
      - fertilizer_2
      - fertilizer_3

  - name: crops
    type: number
    scope: user
    source: user.crops
    values:
      - rabi
      - kharif

  - name: land_area
    type: number
    scope: user
    source: user.land_area

  - name: ctr
    type: rate
    top: click
    bottom: impression
    scope: item
    bucket: 24h
    periods: [7,30]

  - name: liked_fertilizer
    type: interacted_with
    interaction: click
    field: item.fertilizer
    scope: session
    count: 10
    duration: 24h

  - name: visitor_click_count
    type: interaction_count
    interaction: click
    scope: session

  - name: global_item_click_count
    type: interaction_count
    interaction: click
    scope: item

  - name: day_item_click_count
    type: window_count
    interaction: click
    scope: item
    bucket: 24h
    periods: [7,30]